version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3310:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mariadb_data:/var/lib/mysql

  web:
    build: .
    container_name: log-receiver
    command: >
      /bin/bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL || true &&
      gunicorn log_reciever.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      # DATABASE_URL или переменные для подключения к MariaDB
      DATABASE_URL: mysql://root:${MARIADB_ROOT_PASSWORD}@db:3310/${MARIADB_DATABASE}
    ports:
      - "8080:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  mariadb_data: 
  static_volume:
