# Generated by Django 5.2.4 on 2025-07-11 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField()),
                ('error_message', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField(blank=True, default='')),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('initiator', models.CharField(blank=True, default='', max_length=255)),
                ('tab_id', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('request_body', models.BinaryField(blank=True, null=True)),
                ('response', models.BinaryField(blank=True, null=True)),
                ('status_code', models.CharField(blank=True, default='', max_length=10)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('html', models.BinaryField(blank=True, null=True)),
                ('response_time', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['ip_address'], name='logs_collec_ip_addr_5cb65e_idx'), models.Index(fields=['received_at'], name='logs_collec_receive_9b2eff_idx'), models.Index(fields=['url'], name='logs_collec_url_6ffbe4_idx')],
            },
        ),
    ]
