# Generated by Django 5.2.4 on 2025-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='employee',
            field=models.CharField(default='pawka', max_length=255),
            preserve_default=False,
        ),
    ]
